version: '3.8'

x-env: &env
  DB_HOST: postgres
  DB_USER: rh_developer
  DB_PASS: not_secure
  REDIS_HOST: redis
  ELASTICSEARCH_HOST: http://elasticsearch:9200

services:
  helper:
    image: researchhub-backend
    command: sh -c "echo never > /sys/kernel/mm/transparent_hugepage/enabled"
    privileged: true
  postgres:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_DB=researchhub
      - POSTGRES_USER=rh_developer
      - POSTGRES_PASSWORD=not_secure
    volumes:
      - db:/var/lib/postgresql/data
  migrations:
    image: researchhub-backend
    environment: *env
    command: >
      sh -c "
             python manage.py makemigrations &&
             python manage.py migrate"
    depends_on:
      - postgres
  setup:
    image: researchhub-backend
    environment: *env
    command: >
      sh -c "
             python manage.py collectstatic --noinput &&
             python manage.py setup"
    depends_on:
      migrations:
        condition: service_completed_successfully
  backend:
    image: researchhub-backend
    environment: *env
    command: python manage.py runserver 0.0.0.0:8080
    ports:
    - '8000:8080'
    depends_on:
      - migrations
      - elasticsearch
  redis:
    image: researchhub-backend
    restart: always
    ports:
      - '6380:6379'
    command: redis-server --protected-mode no
  celery:
    image: researchhub-backend
    environment: *env
    restart: always
    command: celery -A researchhub worker -Q default,paper_metadata,caches,hot_score,elastic_search,external_reporting,notifications,paper_misc,cermine,twitter,pull_papers,logs,purchases,contributions,author_claim -l info --concurrency=1 --prefetch-multiplier=1 -P prefork  --uid=nobody --gid=nogroup
    depends_on:
      - redis
      - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
    restart: always
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    # Uncomment out this section if you want to see Elasticsearch logs
    # logging:
    #   driver: "none"
volumes:
  db:
    driver: local
  esdata:
    driver: local
