branch-defaults:
  default:
    environment: production
environment-defaults:
  production:
    branch: null
    repository: null
global:
  application_name: researchhub-backend
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-west-2::platform/Python 3.6 running
    on 64bit Amazon Linux/2.9.3
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
